### PR TITLE
Added Docker support

### PR DESCRIPTION
**Pull request by kavanista**
@shane-t @tcob just cos

**docker build -t randomness/ultrachat
docker run -p 4000:4000 -d randomness/ultrachat**

sorted.

### CODE REVIEW

**Comment by kavanista** [comment]
also https://rggtrn.github.io/#RGGTRN for no good reason

**Comment by shane-t** [comment]
⛴️

**Comment by kavanista** [comment]
:shipit:

**Comment by kavanista** [comment]
@tcob @shane-t 
btw you should create a .dockerignore with:

```
cat .dockerignore
node_modules
npm-debug.log
```

**Pull request merged**
